### ISSUE TITLE
Inconsistency between g_profiles clusters and legend

### ISSUE THREAD

**Issue by SebastienNin** [dputhier/dbfmcl#8]
I noticed that the clusters seen on tile plot from plot_clust ranged form 1 to 9. The color of the legend range from 0 to 9 and correspond to Seurat clusters.

**Comment by dputhier** [comment]
I thought this was fixed. Will have a look.

**Comment by dputhier** [comment]
This should be fixed in main:

![image](https://user-images.githubusercontent.com/1831198/126633015-15e4ec1d-c94a-4746-bbf0-9331834041e9.png)

**Comment by SebastienNin** [comment]
I tried it and It's fine.
![image](https://user-images.githubusercontent.com/18463343/126634729-f041cbfb-aac5-4550-bfe4-2b1174cf56ba.png)

Now I have a question!
Are we supposed to have the same number of cluster than in the Seurat object? If yes, there is a problem with the number of clusters. In Seurat, we get 10 clusters where in DBFMCL, we get 9 clusters.

**Comment by dputhier** [comment]
Hi Seb,
Regarding the left diagram (gene profile), on the x-axis (columns) we have the cell clusters (0-9, n=10) as obtained with Seurat. On the y-axis we have the gene cluster (1-9) as found by DBF-MCL. This are these gene cluster that we are interested in annotating. In contrast to what is proposed generally this cluster are obtained in an unsupervised manner (ie. without comparing cell groups. Is that OK ?

**Comment by SebastienNin** [comment]
Yeah I totally misunderstood the figure, sorry for that...

**Comment by dputhier** [comment]
No problem. It needs clarification.

**Comment by dputhier** [comment]
The profiles in the left diagram corresponds to the average profiles of gene clusters.
